---
- name: Setup Home Dockers Environment
  hosts: all
  become: true

  vars:
    repo_url: "https://github.com/your-username/home-dockers.git"
    repo_dir: "/home/{{ ansible_user }}/home-dockers"
    subdirectories:
      - "homeassistant"
      - "media"
      - "networking"
      - "utils"
      - "vaultWarden"

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - git
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Install Docker Compose plugin
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dir }}"
        version: main

    - name: Copy defaults.env to .env for each service
      copy:
        src: "{{ repo_dir }}/defaults.env"
        dest: "{{ repo_dir }}/{{ item }}/.env"
        remote_src: yes
      with_items: "{{ subdirectories }}"
      when: ansible_facts['os_family'] == 'Debian'

    - name: Start Docker services
      shell: |
        cd {{ repo_dir }}/{{ item }}
        docker compose up -d
      with_items: "{{ subdirectories }}"
      args:
        chdir: "{{ repo_dir }}"
