name: monitoring

services:
  netdata:
    image: netdata/netdata
    container_name: netdata
    ports:
      - 19999:19999
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    profiles:
      - donotstart
    ports:
      - "9090:9090"
    volumes:
      - /opt/prometheus/etc:/etc/prometheus
      - /opt/prometheus/data:/prometheus
    restart: unless-stopped
      #    command:
      #      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    profiles:
      - donotstart
    ports:
      - "3003:3000"
    volumes:
      - /opt/grafana/data:/var/lib/grafana
    restart: unless-stopped
    
volumes:
  grafana:
        driver: local
  prometheus:
        driver: local
